version: 2

models:
  - name: stg_user_recent_songs
    columns:
      - name: track_id
        tests:
          - not_null
      - name: artist_id
        tests:
          - not_null
  
  - name: stg_user_top_artists
    columns:
      - name: artist_id
        tests:
          - not_null
          - unique
  
  - name: stg_user_top_tracks
    columns:
      - name: track_id
        tests:
          - not_null
          - unique
      - name: artist_id
        tests:
          - not_null